### ISSUE TITLE
Feature Request: Recipes with Non- and Quasi-Consumables

### ISSUE THREAD

**Issue by ghost** [SvenKayser/JMOD#14]
Recipe configurations should include the ability to determine if any specific item is, instead of being consumed in the recipe, either damaged or completely unharmed.  This would make it possible to add new cooking recipes using Pam's tools, just as an example.

**Comment by SvenKayser** [comment]
Postponed until 1.0.6, but scheduled for implementation

**Comment by SvenKayser** [comment]
Actually "tools" as those from Pam's should remain intact already as the crafting logic employed is the vanilla one, and as such respects items "containing" themselves (that's how that works internally). As of now, only the matching logic is custom to better work with the String-based ItemStack definitiions used in JMOD (mostly to produce less overhead when matching)

**Comment by SvenKayser** [comment]
Postponed.

**Comment by SvenKayser** [comment]
I will take the following approach here - to keep JMOD from going too far astray from what modders will or would expect.

I'll introduce a way to pass on a container item on item creation, as well as have already present items have a container item.

The upside is it allows for items to be created which purpose clearly is to be reused (as a sort of crafting-tool as excessively used in Pam's HC) in a simple and central manner. The downside: This should be handled with care since it will reflect on all recipes such an item is used in.

**Comment by SvenKayser** [comment]
Resolved as of https://github.com/SvenKayser/JMOD/pull/59/commits/c54c09c1f0cf8cfb3f07de6835080b6614395f00
