### ISSUE TITLE
[Documentation] Sample project

### ISSUE THREAD

**Issue by helkarakse** [SvenKayser/JMOD#3]
Do you have a sample project file or a short description on where to put the JS files necessary to be picked up and run as a mod?

**Comment by ghost** [comment]
An example is [here](https://github.com/reteo/Survival-Industry/tree/master/Documents%20and%20Notes/Resource%20Packs/si.core.jmod), in which JMOD is used as the basis for most of the custom features for an upcoming version of Survival Industry.  

Note that the beginning script to be read is identified by the `mod.json` file, and that script then uses the JavaScript `load()` command in order to load up the rest of the scripts.

Once you have all the scripts written, zip them up, along with the assets folder (you know, for textures and language), and change `.zip` to `.jmod`

Once you have `customscripts.jmod` (or whatever you decided to name it), simply put it in the mods folder, and it will be loaded as if it were a regular Forge mod... as long as you have JMOD itself already installed.  It will even show up in the Forge mods list in the main menu.

**Comment by ghost** [comment]
I just finished three sample projects that can be used directly:
- [Vanilla Ingot Works](https://www.dropbox.com/s/1svme43dh3t6jjm/VanillaIngotWorks-1.0.jmod?dl=0) provides everything you need to provide vanilla-style ore doubling, and if you happen to have copper, tin, and silver, it also allows you to make bronze and electrum.
- [Common Ores](https://www.dropbox.com/s/2xokrc0ltgi4d96/CommonOres-1.0.jmod?dl=0) provides the most commonly-used ores by mods, so that those using ore dictionary entries can take advantage of them.  The included ores are Copper, Tin, Silver, Aluminum, Nickel, Platinum, and Lead.  If you have Vanilla Ingot Works as well, this mod includes bronze and electrum.  Additionally, this mod also makes armor and tools available for those metals... including a lead pipe.
- [Chisel-Ztones](https://www.dropbox.com/s/nfaa50ylevv868h/Chisel-Ztones-1.0.jmod?dl=0) is a conversion of the Chizzle Z-Tizzle Minetweaker script that provides all the features, as well as a way to convert a block back to the basic Ztone tile.

You simply place them in the mods folder with JMOD, and that's it.  If you want to alter them, simply unzip them and edit the JavaScript files.  Then zip them back up, change ".zip" to ".jmod", and plop them back into the mods folder.

**Comment by helkarakse** [comment]
Hi reteo, thanks for putting together the files, but I realise now that this is not actually along the lines of what I was looking at. I was under the impression that this mod would function similar to something like Sponge Javascript, permitting you to write simple mods that hooked into Forge. It appears that the functionality is closer to Minetweaker. I'm sorry for the trouble.
